[project]
name = "inex-pipelines"
version = "0.1.0"
description = "ETL pipelines for INEP higher-education microdata"
readme = "README.md"
authors = [
    { name = "rubensantoniorosa2704", email = "rubensrosaneto27@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "polars>=1.43.2",
]

[project.scripts]
inex-pipelines = "inex_pipelines:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
